
name: 'Get File Contents'
on:
  push:
    branches:
      - main
    paths:
      - '**.yaral'
jobs:
  vm:
    name: 'Deploy Rules'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@master
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ';'
      - name: test
        run: |
          echo '${{ steps.file_changes.outputs.files_modified}}'
      - name: run loop
        run: |
          for FILE in ${{ steps.file_changes.outputs.files_modified }}; do curl -XPOST https://quiet-vista-5142.tines.io/webhook/a395fec0dcc9e7de5d5b7ced5d1a9ad3/36855516792bdde4c6aae2a904155313 -d "{\"name\": \"$(ls $FILE | sed 's/rules\///g')\", \"rule\":\"$(base64 $FILE)\"}" -H "Content-Type: application/json"; done
