
name: 'Get File Contents'
on:
  push:
    branches:
      - main
    paths:
      - '**.yaral'
jobs:
  vm:
    name: 'Deploy Rules'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
          echo $GITHUB_ENV
