
name: 'Get File Contents'
on:
  push:
    branches:
      - main
    paths:
      - '**.yaral'
jobs:
  vm:
    name: 'Deploy Rules'
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
